module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: [],
  extends: [
    'react-app',
    'airbnb/hooks',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:json/recommended',
    'plugin:jest/recommended',
    'plugin:testing-library/dom',
    'plugin:jest-dom/recommended',
    'prettier',
  ],
  settings: {
    react: {
      version: '18.3.1',
    },
  },
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    project: './tsconfig.eslint.json',
    tsconfigRootDir: __dirname,
  },
  globals: {
    fetch: true,
  },
  env: {
    browser: true,
    node: true,
    es6: true,
    jest: true,
  },
  rules: {
    'no-plusplus': 'off',
    'spaced-comment': 'off',
    'import/prefer-default-export': 'off',
    'import/no-unresolved': 'off',
    'import/no-extraneous-dependencies': 'off',
    'react/prop-types': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/destructuring-assignment': 'off',
    'class-methods-use-this': 'off',
    'for-direction': 'off',
    'lines-between-class-members': 'off',
    'no-underscore-dangle': 'off',
    'max-classes-per-file': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    'react/require-default-props': 'off',
    'arrow-body-style': 'off',
    'jest-dom/prefer-in-document': 'off',
    'import/order': 'warn',
    'react-hooks/exhaustive-deps': 'warn',
    'react/jsx-sort-props': 'warn',
    'no-console': 'error',
    '@typescript-eslint/no-explicit-any': 'off',
    'testing-library/no-node-access': 'off',
    curly: ['error', 'all'],
    'jest/no-disabled-tests': 'off',
  },
};
